qsub ap/testing/sge/apjob.sh -- citations.txt 2
qsub ap/testing/sge/apjob.sh -- cs-courses.txt 2
qsub ap/testing/sge/apjob.sh -- cs81.txt 2
qsub ap/testing/sge/apjob.sh -- dig.txt 2
qsub ap/testing/sge/apjob.sh -- dtrace.txt 2
qsub ap/testing/sge/apjob.sh -- fenotes.txt 2
qsub ap/testing/sge/apjob.sh -- index.html 2
qsub ap/testing/sge/apjob.sh -- keunning.txt 2
qsub ap/testing/sge/apjob.sh -- ls.txt 2
qsub ap/testing/sge/apjob.sh -- prefs-plist.txt 2
qsub ap/testing/sge/apjob.sh -- sexp.txt 2
qsub ap/testing/sge/apjob.sh -- stems-trimmed.txt 2
qsub ap/testing/sge/apjob.sh -- stems.html 2
qsub ap/testing/sge/apjob.sh -- synthstems-noise.txt 2
qsub ap/testing/sge/apjob.sh -- synthstems.txt 2
qsub ap/testing/sge/apjob.sh -- tiny.txt 2
qsub ap/testing/sge/apjob.sh -- wcstaff-trimmed.txt 2
qsub ap/testing/sge/apjob.sh -- wcstaff.txt 2
qsub ap/testing/sge/apjob.sh -- wikihistory.txt 2
qsub ap/testing/sge/apjob.sh -- citations.txt 5
qsub ap/testing/sge/apjob.sh -- cs-courses.txt 5
qsub ap/testing/sge/apjob.sh -- cs81.txt 5
qsub ap/testing/sge/apjob.sh -- dig.txt 5
qsub ap/testing/sge/apjob.sh -- dtrace.txt 5
qsub ap/testing/sge/apjob.sh -- fenotes.txt 5
qsub ap/testing/sge/apjob.sh -- index.html 5
qsub ap/testing/sge/apjob.sh -- keunning.txt 5
qsub ap/testing/sge/apjob.sh -- ls.txt 5
qsub ap/testing/sge/apjob.sh -- prefs-plist.txt 5
qsub ap/testing/sge/apjob.sh -- sexp.txt 5
qsub ap/testing/sge/apjob.sh -- stems-trimmed.txt 5
qsub ap/testing/sge/apjob.sh -- stems.html 5
qsub ap/testing/sge/apjob.sh -- synthstems-noise.txt 5
qsub ap/testing/sge/apjob.sh -- synthstems.txt 5
qsub ap/testing/sge/apjob.sh -- tiny.txt 5
qsub ap/testing/sge/apjob.sh -- wcstaff-trimmed.txt 5
qsub ap/testing/sge/apjob.sh -- wcstaff.txt 5
qsub ap/testing/sge/apjob.sh -- wikihistory.txt 5
qsub ap/testing/sge/apjob.sh -- citations.txt 10
qsub ap/testing/sge/apjob.sh -- cs-courses.txt 10
qsub ap/testing/sge/apjob.sh -- cs81.txt 10
qsub ap/testing/sge/apjob.sh -- dig.txt 10
qsub ap/testing/sge/apjob.sh -- dtrace.txt 10
qsub ap/testing/sge/apjob.sh -- fenotes.txt 10
qsub ap/testing/sge/apjob.sh -- index.html 10
qsub ap/testing/sge/apjob.sh -- keunning.txt 10
qsub ap/testing/sge/apjob.sh -- ls.txt 10
qsub ap/testing/sge/apjob.sh -- prefs-plist.txt 10
qsub ap/testing/sge/apjob.sh -- sexp.txt 10
qsub ap/testing/sge/apjob.sh -- stems-trimmed.txt 10
qsub ap/testing/sge/apjob.sh -- stems.html 10
qsub ap/testing/sge/apjob.sh -- synthstems-noise.txt 10
qsub ap/testing/sge/apjob.sh -- synthstems.txt 10
qsub ap/testing/sge/apjob.sh -- tiny.txt 10
qsub ap/testing/sge/apjob.sh -- wcstaff-trimmed.txt 10
qsub ap/testing/sge/apjob.sh -- wcstaff.txt 10
qsub ap/testing/sge/apjob.sh -- wikihistory.txt 10
